export const apiKey = 'DEIN-API-KEY';

export const weatherImages = {
    'Partly cloudy': require('../assets/images/partlycloudy.png'),
    'Patchy rain nearby': require('../assets/images/moderaterain.png'),
    'Patchy rain possible': require('../assets/images/moderaterain.png'),
    'Patchy light rain with thunder': require('../assets/images/heavyrain.png'),
    'Sunny': require('../assets/images/sun.png'),
    'Clear': require('../assets/images/sun.png'),
    'Overcast': require('../assets/images/cloud.png'),
    'Cloudy': require('../assets/images/cloud.png'),
    'Torrential rain shower': require('../assets/images/heavyrain.png'),
    'Light rain': require('../assets/images/moderaterain.png'),
    'Light drizzle': require('../assets/images/moderaterain.png'),
    'Light rain shower': require('../assets/images/moderaterain.png'),
    'Heavy rain': require('../assets/images/heavyrain.png'),
    'Heavy rain at times': require('../assets/images/heavyrain.png'),
    'Moderate rain': require('../assets/images/moderaterain.png'),
    'Moderate rain at times': require('../assets/images/moderaterain.png'),
    'Moderate or heavy freezing rain': require('../assets/images/heavyrain.png'),
    'Moderate or heavy rain shower': require('../assets/images/heavyrain.png'),
    'Moderate or heavy rain with thunder': require('../assets/images/heavyrain.png'),
    'Mist': require('../assets/images/mist.png'),
    'Blowing snow': require('../assets/images/sun.png'),
    'Blizzard': require('../assets/images/sun.png'),
    'Fog': require('../assets/images/sun.png'),
    'Freezing fog': require('../assets/images/sun.png'),
    'Patchy light drizzle': require('../assets/images/sun.png'),
    'Freezing drizzle': require('../assets/images/sun.png'),
    'Heavy freezing drizzle': require('../assets/images/sun.png'),
    'Patchy light rain': require('../assets/images/sun.png'),
    'Moderate rain at times': require('../assets/images/sun.png'),
    'Heavy rain': require('../assets/images/sun.png'),
    'Light freezing rain': require('../assets/images/sun.png'),
    'Light sleet': require('../assets/images/sun.png'),
    'Moderate or heavy freezing rain': require('../assets/images/sun.png'),
    'Moderate or heavy sleet': require('../assets/images/sun.png'),
    'Patchy light snow': require('../assets/images/sun.png'),
    'Light snow': require('../assets/images/sun.png'),
    'Patchy moderate snow': require('../assets/images/sun.png'),
    'Moderate snow': require('../assets/images/sun.png'),
    'Patchy heavy snow': require('../assets/images/sun.png'),
    'Heavy snow': require('../assets/images/sun.png'),
    'Ice pellets': require('../assets/images/sun.png'),
    'Light rain shower': require('../assets/images/sun.png'),
    'Moderate or heavy rain shower': require('../assets/images/sun.png'),
    'Torrential rain shower': require('../assets/images/sun.png'),
    'Light sleet showers': require('../assets/images/sun.png'),
    'Moderate or heavy sleet showers': require('../assets/images/sun.png'),
    'Light snow showers': require('../assets/images/sun.png'),
    'Moderate or heavy snow showers': require('../assets/images/sun.png'),
    'Light showers of ice pellets': require('../assets/images/sun.png'),
    'Moderate or heavy showers of ice pellets': require('../assets/images/sun.png'),
    'Patchy light rain with thunder': require('../assets/images/sun.png'),
    'Moderate or heavy rain with thunder': require('../assets/images/sun.png'),
    'Patchy light snow with thunder': require('../assets/images/sun.png'),
    'Moderate or heavy snow with thunder': require('../assets/images/sun.png'),
    'other': require('../assets/images/moderaterain.png')
}